### PR TITLE
Fix packaging of data files

### PR DESCRIPTION
**Pull request by klemens**
This updates to the `1.2.post3` tag, which fixes the problems with the i.a. language files that were installed into the wrong location.

### CODE REVIEW

**Comment by StreakyCobra** [comment]
@klemens Can you rebase on the last commit and test if both desktop entry and languages issues are fixed?

If yes I'll merge your commit and push to AUR.

**Comment by StreakyCobra** [comment]
@Lucki @klemens Sorry for delegating that much, it's an exceptional situation, usually I would have deal with all this myself. Thanks for your help.

**Comment by klemens** [comment]
Rebase onto master. I also removed the version field in the desktop file and moved the icon to the correct path (see the discussion in #1).

Everything seems to work, the language pack is loaded correctly and the icon shows up in gnome with the correct name and categories etc.

**Comment by StreakyCobra** [comment]
I don't have access to an Archlinux machine until next week, so I will trust you :-)

Uploaded to AUR. Thanks a lot.

**Pull request merged**
